### PR TITLE
Tooltip tweaks

### LINKED ISSUE #23: Tooltip design improvements
* Make the name gradient stronger
* Update border color according to the card's rarity

### PR DESCRIPTION
**Pull request by Zhouzi**
Close #23 #25 #26

### CODE REVIEW

**Comment by Zhouzi** [comment]
I fixed the few issues and improved positioning. Also tweaked the design a bit, although I'm still not really happy about it.



Anyway, ready to merge @Soreine 👍

**Comment by Zhouzi** [comment]
After further testing, the tooltip is weirdly positioned under certain circumstances.

**Comment by Zhouzi** [comment]
Okay so I wasn't properly removing previous position properties. I also removed the vertical align logic, which means the tooltip will always be positioned the same way vertically. It's just going to be placed left/right depending on where there's more room. Vertical alignment leads to inconsistent position which looks weird. Since the tooltips have a `transform: translateY(-40%)`, their height shouldn't be an issue. You might need to scroll anyway.

**Comment by Soreine** [comment]
I could not experiment with vertical adjustment, none of the commits I tested seemed to implement it.
But we need to do something about it. Having to scroll down is annoying. I think the wrapper should stay as a position wrapper for the span of text and not move. Then we compute the bottom and left bounds of the card tooltip itself, and translate it according to that.

**Comment by Zhouzi** [comment]
Yep, it can be easily improved, I was just too lazy 😛

**Pull request merged**
