### PR TITLE
Detect card names

### LINKED ISSUE #2: Build a dictionnary of cards names (and game terms eventually)
To be able to recognize them in the page

Questions:
- Take it from https://api.gwentapi.com/v0/cards?limit=999 ?
  - Manual and requires a new extension version everytime the game is updated?
  - Automatic at Chrome startup, with caching?
  - other ?
- How to keep it up to date ?
- How to add aliases etc. ?

### LINKED ISSUE #3: How to efficiently detect card names inside an HTML document
- Restrict the extension to a list of enabled websites
- Use appropriate data structure for the card name dictionary (see variations of https://en.wikipedia.org/wiki/Trie)
- Case insensitive ? Typo insensitive ? 
- Restrict algorithm on hovering paragraphs of text ?

### PR DESCRIPTION
**Pull request by Soreine**
Goal is to:
- Close #2 
- Close #3

### CODE REVIEW

**Comment by Zhouzi** [comment]
Close #12

**Comment by Zhouzi** [comment]
I moved support for acronyms and aliases into separate issues #13 #14. That way this PR can be merged sooner and we can tackle #15 to test the extension.

**Comment by Soreine** [comment]
I'll make the typo detection in another PR

**Comment by Soreine** [comment]
thx

**Pull request merged**
