### PR TITLE
Extension adds tooltips

### PR DESCRIPTION
**Pull request by Soreine**
A big object exported in `CARDS.js`, with card names as keys, and card data as values.

I'm going to try to use this to make the extension add tooltips to the page.

### CODE REVIEW

**Comment by Soreine** [comment]
It now adds tooltips in the page.

**Comment by Soreine** [comment]
screen shot 2017-07-23 at 15 12 49
screen shot 2017-07-23 at 15 12 57
screen shot 2017-07-23 at 15 13 06

**Comment by Soreine** [comment]
There's still an issue. When attaching the tooltips, it seems to load all the images (not waiting for mouse hover)

**Comment by Soreine** [comment]
I improved the detection of word starts. So that this is still detect:

> Mardroeme/Ciri

**Comment by Zhouzi** [comment]
Dang, the tooltip looks so bad on a dark background 🤦‍♂️ 

Will have to improve that further!

**Pull request merged**
